# Generated by Django 3.0.2 on 2020-01-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutGoingSlack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('msg', models.TextField()),
                ('indexOfCommit', models.CharField(max_length=100)),
                ('commitUrl', models.TextField()),
                ('repository', models.CharField(max_length=100)),
                ('repositoryUrl', models.TextField()),
            ],
        ),
    ]
